Repository tengstrand/lein-polylith, pull requests merged in 2019-02, with the labels that each got.

#28 Sync system libraries based on the components (and bases) they depend on
  src/leiningen/polylith/cmd/sync/systems.clj
  test/leiningen/polylith/cmd/sync_test.clj
Labels: bug

#32 Fixes alphabetical ordering of dependencies during sync
  project.clj
  src/leiningen/polylith/file.clj
  test/leiningen/polylith/cmd/sync_test.clj
Labels: enhancement

#33 Release/v0.2.2
  project.clj
  readme.md
  src/leiningen/polylith/version.clj
Labels: release
